# Generated by Django 5.2.5 on 2025-08-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prism',
            name='type',
            field=models.CharField(default='Rectangular', max_length=100),
        ),
    ]
