# Generated by Django 5.2.5 on 2025-08-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisms', '0002_prism_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prism',
            name='name',
        ),
        migrations.RemoveField(
            model_name='prism',
            name='type',
        ),
        migrations.AddField(
            model_name='prism',
            name='designation',
            field=models.CharField(default='L40B20H100', max_length=50),
        ),
        migrations.AddField(
            model_name='prism',
            name='prism_name',
            field=models.CharField(default='rectangular', max_length=50),
        ),
    ]
